[build]
  command = "npm install && npm start"
  publish = "public"  # Create a public folder for static assets
  
[template.environment]
  SITE_LOCATION = "Enter the path to your HTML files"
  API_KEY = "Enter your secret API key"