[build]
  command = "echo Building Functions"
  publish = "public"
  functions = "netlify"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["express"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200